# org: ikiningyou
# app: nas-server
service: nas-server-lambda
frameworkVersion: "3"
configValidationMode: error

provider: ${file(./settings/dev/provider.yml):provider}
functions: ${file(./settings/dev/functions/functions.yml):functions}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-enable-api-logs

package:
  patterns:
    - src/**

custom:
  serverless-offline:
    httpPort: 4000

